import mysql from 'mysql2/promise';import bcrypt from 'bcryptjs';import fs from 'fs';import path from 'path';import {fileURLToPath} from 'url';
const root=path.dirname(fileURLToPath(import.meta.url));const env=Object.fromEntries(fs.readFileSync(path.join(root,'..','.env'),'utf8').split(/\r?\n/).filter(x=>x&& !x.startsWith('#')).map(x=>{const i=x.indexOf('=');return [x.slice(0,i),x.slice(i+1)]}));const c=await mysql.createConnection({host:env.DB_HOST||'localhost',port:Number(env.DB_PORT||3306),user:env.DB_USER||'root',password:env.DB_PASSWORD||'',database:env.DB_NAME||'vnlibrary'});await c.query('SET FOREIGN_KEY_CHECKS=0');for(const t of ['fines','purchases','reservations','borrows','books','readers','categories','users'])await c.query(`TRUNCATE TABLE ${t}`);await c.query('SET FOREIGN_KEY_CHECKS=1');
const cats=['Văn học','Khoa học','Công nghệ','Kinh tế','Lịch sử','Tâm lý','Ngoại ngữ','Giáo dục','Thiếu nhi','Kỹ năng sống','Nghệ thuật','Triết học'];for(const n of cats)await c.query('INSERT INTO categories(name,description) VALUES(?,?)',[n,'Tài liệu thuộc nhóm '+n]);
const admin=await bcrypt.hash('Admin@123',10);await c.query('INSERT INTO users(name,email,password_hash,phone,role) VALUES(?,?,?,?,"ADMIN")',['Quản trị viên','admin@vnlibrary.vn',admin,'0900000000']);
const first=['Nguyễn Minh Anh','Trần Quốc Bảo','Lê Hoàng Nam','Phạm Thu Hà','Võ Gia Huy','Đặng Ngọc Mai','Bùi Thanh Tùng','Phan Khánh Linh','Đỗ Đức Anh','Hoàng Minh Châu','Ngô Hải Yến','Vũ Thành Long','Đinh Quang Huy','Hồ Ngọc Lan','Dương Nhật Minh','Mai Phương Thảo','Trương Tuấn Kiệt','Lý Thanh Vy','Cao Minh Khang','Tạ Bảo Ngọc'];for(let i=0;i<287;i++){const name=first[i%first.length].replace(/\s+/g,' ')+' '+['An','Bình','Chi','Dũng','Giang','Hạnh','Khoa','Linh','Nam','Oanh','Phúc','Quân','Sơn','Trang'][Math.floor(i/first.length)%14];await c.query('INSERT INTO readers(name,email,phone,address) VALUES(?,?,?,?)',[name,`docgia${i+1}@vnlibrary.local`,`09${String(10000000+i).slice(0,8)}`,'Đà Nẵng']);}
const titles=['Những ngày thơ ấu','Dế Mèn phiêu lưu ký','Tôi thấy hoa vàng trên cỏ xanh','Tuổi trẻ đáng giá bao nhiêu','Nhà giả kim','Đắc nhân tâm','Lược sử thời gian','Clean Code','Java cơ bản','Cơ sở dữ liệu','Lập trình web hiện đại','Kỹ năng giao tiếp','Tư duy nhanh và chậm','Sapiens','Sherlock Holmes'];const authors=['Nguyễn Nhật Ánh','Tô Hoài','Robert Kiyosaki','Paulo Coelho','Dale Carnegie','Stephen Hawking','Robert C. Martin','Nguyễn Văn A','Yuval Noah Harari','Arthur Conan Doyle'];for(let i=0;i<1213;i++){const title=titles[i%titles.length]+' – Tập '+(Math.floor(i/titles.length)+1);const qty=1+(i%7);const cat=(i%cats.length)+1;const price=45000+(i%12)*15000;await c.query('INSERT INTO books(title,author,isbn,publisher,year,category_id,quantity,available,price) VALUES(?,?,?,?,?,?,?,?,?)',[title,authors[i%authors.length],`978604${String(1000000+i).slice(-7)}`,'VNLibrary Publishing',2015+(i%11),cat,qty,qty,price]);}
// 119 active borrows, of which 21 are overdue. Borrow one copy from each selected book.
for(let i=0;i<119;i++){const reader=i+1,book=i+1;const overdue=i<21;const due=new Date();due.setDate(due.getDate()-(overdue?(i%12+1):-(i%10+2)));const iso=due.toISOString().slice(0,10);await c.query('INSERT INTO borrows(reader_id,book_id,borrow_date,due_date,status) VALUES(?,?,DATE_SUB(CURDATE(),INTERVAL 7 DAY),?,"BORROWING")',[reader,book,iso]);await c.query('UPDATE books SET available=GREATEST(available-1,0) WHERE id=?',[book]);}
for(let i=0;i<21;i++){const b=i+1,r=i+1;const days=i%12+1;const amount=days*5000;const [x]=await c.query('SELECT id FROM borrows WHERE id=?',[b]);if(x.length)await c.query('INSERT INTO fines(borrow_id,reader_id,amount,reason,status) VALUES(?,?,?,?,"UNPAID")',[b,r,amount,'Trả sách quá hạn']);}
await c.end();console.log('Seed complete: 1213 books, 287 readers, 119 borrowing, 21 overdue.');
