'use client';
import {useEffect,useState} from 'react';import {useRouter} from 'next/navigation';import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,LineChart,Line} from 'recharts';
const menu=[['dashboard','Tổng quan','📊'],['books','Quản lý sách','📚'],['inventory','Kho sách','📦'],['readers','Độc giả','👥'],['categories','Thể loại','🏷️'],['borrows','Mượn / trả','🔄'],['reservations','Đặt trước','🔖'],['purchases','Mua sách','🛒'],['payments','Thanh toán','💳'],['fines','Tiền phạt','💰'],['reports','Báo cáo','📈'],['notifications','Thông báo','🔔'],['users','Tài khoản','👤'],['settings','Cài đặt','⚙️']];
type Any=any;
export default function Dashboard(){const [user,setUser]=useState<Any>(null),[section,setSection]=useState('dashboard'),[stats,setStats]=useState<Any>({}),[data,setData]=useState<Any[]>([]),[cats,setCats]=useState<Any[]>([]),[search,setSearch]=useState(''),[modal,setModal]=useState<Any>(null),[toast,setToast]=useState(''),[report,setReport]=useState<Any>({cats:[],borrows:[],top:[]});const r=useRouter();
useEffect(()=>{fetch('/api/categories').then(x=>x.json()).then(j=>setCats(Array.isArray(j)?j:[]));fetch('/api/auth/me').then(x=>x.json()).then(j=>{if(!j.user)r.push('/login');else setUser(j.user)});load('dashboard');load('reports')},[]);
useEffect(()=>{if(section==='dashboard')load('dashboard');else if(section==='reports')load('reports');else if(section==='categories')load('categories');else if(['books','inventory'].includes(section))load('books');else if(section==='readers')load('readers');else if(section==='borrows')load('borrows');else if(section==='reservations')load('reservations');else if(['purchases','payments'].includes(section))load('purchases');else if(section==='fines')load('fines');else if(section==='notifications')load('notifications');else if(section==='users')load('users')},[section,search]);
async function load(s:string){try{if(s==='dashboard'){const j=await (await fetch('/api/dashboard')).json();setStats(j.stats||{})}else{const u=s==='books'?`/api/books?q=${encodeURIComponent(search)}`:`/api/${s}`;const j=await (await fetch(u)).json();if(s==='reports')setReport(j);else setData(Array.isArray(j)?j:[])}}catch{setToast('Không tải được dữ liệu')}}
async function save(e:any){e.preventDefault();const form=new FormData(e.currentTarget);const body:any=Object.fromEntries(form.entries());let endpoint='/api/'+modal.type,method=modal.id?'PUT':'POST';if(modal.id)endpoint+=`/${modal.id}`;if(modal.type==='books')body.quantity=Number(body.quantity);const x=await fetch(endpoint,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await x.json();if(!x.ok){setToast(j.error||'Có lỗi');return}const savedType=modal.type;setModal(null);setToast('Đã lưu thành công');if(savedType==='categories'){const c=await (await fetch('/api/categories')).json();setCats(Array.isArray(c)?c:[]);load('categories')}else{load(savedType==='books'?'books':savedType)}}
async function action(url:string,method='POST',body?:Any){const x=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await x.json();setToast(x.ok?'Đã cập nhật thành công':(j.error||'Có lỗi'));load(section==='payments'||section==='purchases'?'purchases':section)}
function add(type:string){setModal({type})}function title(){return menu.find(x=>x[0]===section)?.[1]||'Tổng quan'}
if(!user)return <div className="empty">Đang tải VNLibrary...</div>;return <div className="shell"><aside className="side"><div className="brand">📚 VNLibrary</div><div className="nav">{menu.map(m=><button key={m[0]} className={section===m[0]?'active':''} onClick={()=>setSection(m[0])}>{m[2]} <span>{m[1]}</span></button>)}</div></aside><main className="main"><header className="top"><div><b>{title()}</b><div className="muted">Hệ thống quản lý thư viện</div></div><div>{user.name} · {user.role==='ADMIN'?'Quản trị viên':user.role==='LIBRARIAN'?'Thủ thư':'Độc giả'} <button className="btn" onClick={async()=>{await fetch('/api/auth/logout',{method:'POST'});r.push('/login')}}>Đăng xuất</button></div></header><section className="content">{toast&&<div className="notice" onClick={()=>setToast('')}>{toast}</div>}
{section==='dashboard'&&<Home stats={stats}/>} {section==='reports'&&<Reports report={report}/>} 
{['books','inventory'].includes(section)&&<Books data={data} cats={cats} search={search} setSearch={setSearch} add={()=>add('books')} edit={(x:any)=>setModal({...x,type:'books'})} remove={(id:number)=>action('/api/books/'+id,'DELETE')}/>} 
{section==='readers'&&<Readers data={data} search={search} setSearch={setSearch} add={()=>add('readers')} edit={(x:any)=>setModal({...x,type:'readers'})} remove={(id:number)=>action('/api/readers/'+id,'DELETE')}/>} 
{section==='categories'&&<Categories data={data} add={()=>add('categories')} remove={(id:number)=>action('/api/categories/'+id,'DELETE')}/>} 
{section==='borrows'&&<Borrows data={data} add={()=>add('borrows')} action={action}/>} 
{section==='reservations'&&<Simple data={data} title="Danh sách đặt trước" add={()=>add('reservations')} cols={['id','reader_name','book_title','reserve_date','status']}/>} 
{['purchases','payments'].includes(section)&&<Purchases data={data} add={()=>add('purchases')} pay={(id:number)=>action('/api/purchases/'+id+'/pay')}/>} 
{section==='fines'&&<Fines data={data} pay={(id:number)=>action('/api/fines','PATCH',{id})}/>} {section==='notifications'&&<Notifications data={data}/>} {section==='users'&&<Users data={data} action={action}/>} 
{section==='settings'&&<div className="card"><h2>Cài đặt hệ thống</h2><p>VNLibrary sử dụng MySQL trực tiếp qua <b>mysql2</b>, không dùng Prisma.</p><p>Ngôn ngữ: Tiếng Việt · Múi giờ: Asia/Ho_Chi_Minh · Phiên bản: 5.0.0</p></div>}
</section>{modal&&<Modal data={modal} cats={cats} close={()=>setModal(null)} save={save}/>}</main></div>}
function Home({stats}:Any){return <><h1>Tổng quan</h1><div className="grid">{[['Tổng số sách',stats.books||0,'📚'],['Độc giả',stats.readers||0,'👥'],['Đang mượn',stats.borrows||0,'🔄'],['Quá hạn',stats.overdue||0,'⚠️']].map(x=><div className="card" key={x[0]}><div>{x[2]} {x[0]}</div><div className="stat">{x[1]}</div></div>)}</div><div className="grid" style={{marginTop:16}}><div className="card"><div>Doanh thu đã thanh toán</div><div className="stat">{Number(stats.revenue||0).toLocaleString('vi-VN')} ₫</div></div><div className="card"><div>Tiền phạt chưa thu</div><div className="stat danger-text">{Number(stats.unpaidFines||0).toLocaleString('vi-VN')} ₫</div></div></div><div className="card" style={{marginTop:16}}><h3>Hệ thống đã sẵn sàng</h3><p>✅ MySQL + mysql2 · Không Prisma</p><p>✅ Đăng nhập · Đăng ký · Quên mật khẩu</p><p>✅ Sách · độc giả · mượn trả · đặt trước · mua sách · thanh toán · phạt · báo cáo</p></div></>}
function Books({data,cats,search,setSearch,add,edit,remove}:Any){return <><div className="toolbar"><div><h1>Quản lý sách</h1><span className="muted">Tìm kiếm và lọc theo thể loại</span></div><button className="primary" onClick={add}>+ Thêm sách</button></div><div className="toolbar"><input placeholder="Tìm sách..." value={search.startsWith('__CAT__')?'':search} onChange={e=>setSearch(e.target.value)}/><select value={search.startsWith('__CAT__')?search.slice(7):''} onChange={e=>setSearch(e.target.value?`__CAT__${e.target.value}`:'')}><option value="">Tất cả thể loại</option>{cats.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div className="table-card"><table><thead><tr><th>ID</th><th>Tên sách</th><th>Tác giả</th><th>Thể loại</th><th>SL</th><th>Còn</th><th>Giá</th><th>Thao tác</th></tr></thead><tbody>{data.map((x:any)=><tr key={x.id}><td>{x.id}</td><td><b>{x.title}</b><br/><small>{x.isbn||'Chưa có ISBN'}</small></td><td>{x.author}</td><td>{x.category_name||'Chưa phân loại'}</td><td>{x.quantity}</td><td>{x.available}</td><td>{Number(x.price).toLocaleString('vi-VN')} ₫</td><td><div className="actions"><button className="btn" onClick={()=>edit(x)}>Sửa</button><button className="btn danger" onClick={()=>remove(x.id)}>Xóa</button></div></td></tr>)}</tbody></table>{!data.length&&<div className="empty">Không có dữ liệu</div>}</div></>}
function Readers({data,search,setSearch,add,edit,remove}:Any){return <><div className="toolbar"><h1>Độc giả</h1><button className="primary" onClick={add}>+ Thêm độc giả</button></div><div className="toolbar"><input placeholder="Tìm độc giả..." value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="table-card"><table><thead><tr><th>ID</th><th>Họ tên</th><th>Email</th><th>Điện thoại</th><th>Địa chỉ</th><th>Thao tác</th></tr></thead><tbody>{data.map((x:any)=><tr key={x.id}><td>{x.id}</td><td><b>{x.name}</b></td><td>{x.email||'—'}</td><td>{x.phone||'—'}</td><td>{x.address||'—'}</td><td><button className="btn" onClick={()=>edit(x)}>Sửa</button> <button className="btn danger" onClick={()=>remove(x.id)}>Xóa</button></td></tr>)}</tbody></table></div></>}
function Categories({data,add,remove}:Any){return <><div className="toolbar"><h1>Thể loại sách</h1><button className="primary" onClick={add}>+ Thêm thể loại</button></div><div className="grid">{data.map((x:any)=><div className="card" key={x.id}><h3>🏷️ {x.name}</h3><p className="muted">{x.description||'Không có mô tả'}</p><b>{x.book_count} cuốn sách</b><div style={{marginTop:12}}><button className="btn danger" onClick={()=>remove(x.id)}>Xóa</button></div></div>)}</div></>}
function Borrows({data,add,action}:Any){return <><div className="toolbar"><h1>Mượn / trả sách</h1><button className="primary" onClick={add}>+ Lập phiếu mượn</button></div><div className="table-card"><table><thead><tr><th>ID</th><th>Độc giả</th><th>Sách</th><th>Ngày mượn</th><th>Hạn trả</th><th>Trạng thái</th><th></th></tr></thead><tbody>{data.map((x:any)=><tr key={x.id}><td>{x.id}</td><td>{x.reader_name}</td><td>{x.book_title}</td><td>{new Date(x.borrow_date).toLocaleDateString('vi-VN')}</td><td>{new Date(x.due_date).toLocaleDateString('vi-VN')}</td><td><span className={'badge '+(x.status==='BORROWING'?'green':'')}>{x.status==='BORROWING'?'Đang mượn':'Đã trả'}</span>{x.status==='BORROWING'&&new Date(x.due_date)<new Date()&&<span className="badge red"> Quá hạn</span>}</td><td>{x.status==='BORROWING'&&<button className="btn" onClick={()=>action('/api/borrows/'+x.id+'/return')}>Trả sách</button>}</td></tr>)}</tbody></table></div></>}
function Purchases({data,add,pay}:Any){return <><div className="toolbar"><h1>Mua sách & thanh toán</h1><button className="primary" onClick={add}>+ Tạo đơn mua</button></div><div className="table-card"><table><thead><tr><th>ID</th><th>Độc giả</th><th>Sách</th><th>SL</th><th>Tổng tiền</th><th>Trạng thái</th><th></th></tr></thead><tbody>{data.map((x:any)=><tr key={x.id}><td>{x.id}</td><td>{x.reader_name}</td><td>{x.book_title}</td><td>{x.quantity}</td><td>{Number(x.total_amount).toLocaleString('vi-VN')} ₫</td><td>{x.status==='PAID'?<span className="badge green">Đã thanh toán</span>:<span className="badge">Chờ thanh toán</span>}</td><td>{x.status!=='PAID'&&<button className="btn" onClick={()=>pay(x.id)}>Thanh toán</button>}</td></tr>)}</tbody></table></div></>}
function Fines({data,pay}:Any){return <><h1>Tiền phạt</h1><div className="table-card"><table><thead><tr><th>ID</th><th>Độc giả</th><th>Số tiền</th><th>Lý do</th><th>Trạng thái</th><th></th></tr></thead><tbody>{data.map((x:any)=><tr key={x.id}><td>{x.id}</td><td>{x.reader_name}</td><td>{Number(x.amount).toLocaleString('vi-VN')} ₫</td><td>{x.reason}</td><td>{x.status==='PAID'?<span className="badge green">Đã thu</span>:<span className="badge red">Chưa thu</span>}</td><td>{x.status==='UNPAID'&&<button className="btn" onClick={()=>pay(x.id)}>Đã thanh toán</button>}</td></tr>)}</tbody></table></div></>}
function Notifications({data}:Any){return <><h1>Thông báo</h1><div className="grid">{data.map((x:any)=><div className="card" key={x.id}>🔔 <b>{x.reader_name}</b><p>{x.book_title}</p><span className="badge red">Hạn trả: {new Date(x.due_date).toLocaleDateString('vi-VN')}</span></div>)}</div></>}
function Users({data,action}:Any){return <><h1>Tài khoản</h1><div className="table-card"><table><thead><tr><th>ID</th><th>Họ tên</th><th>Email</th><th>Vai trò</th><th>Trạng thái</th><th></th></tr></thead><tbody>{data.map((x:any)=><tr key={x.id}><td>{x.id}</td><td>{x.name}</td><td>{x.email}</td><td>{x.role}</td><td>{x.status}</td><td><button className="btn" onClick={()=>action('/api/users','PATCH',{id:x.id,status:x.status==='ACTIVE'?'LOCKED':'ACTIVE'})}>{x.status==='ACTIVE'?'Khóa':'Mở khóa'}</button></td></tr>)}</tbody></table></div></>}
function Simple({data,title,add,cols}:Any){return <><div className="toolbar"><h1>{title}</h1><button className="primary" onClick={add}>+ Thêm</button></div><div className="table-card"><table><thead><tr>{cols.map((c:string)=><th key={c}>{c}</th>)}</tr></thead><tbody>{data.map((x:any)=><tr key={x.id}>{cols.map((c:string)=><td key={c}>{x[c]||'—'}</td>)}</tr>)}</tbody></table></div></>}
function Reports({report}:Any){return <><h1>Báo cáo & thống kê</h1><div className="card"><h3>Số sách theo thể loại</h3><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={report.cats||[]}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="total"/></BarChart></ResponsiveContainer></div></div><div className="card" style={{marginTop:16}}><h3>Lượt mượn theo tháng</h3><div className="chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={[...(report.borrows||[])].reverse()}><XAxis dataKey="month"/><YAxis/><Tooltip/><Line type="monotone" dataKey="total"/></LineChart></ResponsiveContainer></div></div></>}
function Modal({data,cats,close,save}:Any){const isBook=data.type==='books',isReader=data.type==='readers',isCat=data.type==='categories',isBorrow=data.type==='borrows',isPurchase=data.type==='purchases',isRes=data.type==='reservations';return <div className="modal-bg"><form className="modal" onSubmit={save}><button type="button" className="close" onClick={close}>×</button><h2>{data.id?'Chỉnh sửa':'Thêm mới'}</h2>{isBook&&<><Field n="title" l="Tên sách" v={data.title}/><Field n="author" l="Tác giả" v={data.author}/><div className="row"><Field n="isbn" l="ISBN" v={data.isbn}/><Field n="year" l="Năm xuất bản" v={data.year}/></div><div className="row"><Field n="quantity" l="Số lượng" v={data.quantity||1} t="number"/><Field n="price" l="Giá" v={data.price||0} t="number"/></div><label>Thể loại<select name="category_id" defaultValue={data.category_id||''}><option value="">Chưa phân loại</option>{cats.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><Field n="publisher" l="Nhà xuất bản" v={data.publisher}/></>}{isReader&&<><Field n="name" l="Họ và tên (không chứa số)" v={data.name}/><Field n="email" l="Email" v={data.email}/><Field n="phone" l="Điện thoại" v={data.phone}/><Field n="address" l="Địa chỉ" v={data.address}/></>}{isCat&&<><Field n="name" l="Tên thể loại" v={data.name}/><Field n="description" l="Mô tả" v={data.description}/></>}{isBorrow&&<><Field n="reader_id" l="ID độc giả" t="number"/><Field n="book_id" l="ID sách" t="number"/><Field n="due_date" l="Hạn trả" t="date"/></>}{isPurchase&&<><Field n="reader_id" l="ID độc giả" t="number"/><Field n="book_id" l="ID sách" t="number"/><Field n="quantity" l="Số lượng" t="number" v="1"/></>}{isRes&&<><Field n="reader_id" l="ID độc giả" t="number"/><Field n="book_id" l="ID sách" t="number"/></>}<button className="primary">Lưu</button></form></div>}
function Field({n,l,v,t='text'}:Any){return <label>{l}<input name={n} type={t} defaultValue={v??''} required={['title','name','reader_id','book_id','due_date','quantity'].includes(n)}/></label>}
